# Generated by Django 5.1.5 on 2025-01-30 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default='CODIGO123', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='O código do produto deve conter apenas letras e números.', regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
